networks:
  mojaloop-net:
    name: mojaloop-net


services:
  core-connector: 
    build:
      context: ./src/
    image: mojaloop/mtn-ug-core-connector:v1.22.0 # edit this line
    networks:
      - mojaloop-net
    env_file: .env.example
    ports:
      - "3003:3003" 
      - "3004:3004" 

  TtkBackend:
    networks:
      - mojaloop-net 
    ## TODO: Change the following version to standard version
    image: mojaloop/ml-testing-toolkit:v18.7.4
    # image: mojaloop/ml-testing-toolkit:v16.1.0-snapshot.3
    user: root
    volumes:
      - "./config/ttksim/spec_files:/opt/app/spec_files"
      - "./config/ttksim/environments:/opt/app/examples/environments"
    ports:
      - "4040:4040"
      - "5050:5050"
    environment:
      - AUTH_ENABLED=FALSE
    command: npm start
    healthcheck:
      test: ["CMD-SHELL", "nc localhost 4040"]
      interval: 5s
      timeout: 10s
      retries: 3

  TtkUi:
    image: mojaloop/ml-testing-toolkit-ui:v16.1.1
    ports:
      - "6060:6060"
    networks:
      - mojaloop-net
    environment:
      - API_BASE_URL=http://localhost:5050
      - AUTH_ENABLED=FALSE
    command:
      - sh
      - /usr/share/nginx/start.sh